collab_messages/urls.py
from django.conf.urls import url
from . import views


app_name="collab_messages"
urlpatterns = [
    url(r"^inbox/$", views.CollabInboxView.as_view(),
        name="inbox"),
    url(r"^create/$", views.CollabMessageCreateView.as_view(),
        name="message_create"),
    url(r"^create/(?P<user_id>\d+)/$", views.CollabMessageCreateView.as_view(),
        name="message_user_create"),

    url(r"^thread/(?P<pk>\d+)/$", views.CollabThreadView.as_view(),
        name="thread_detail"),
    url(r"^thread/(?P<pk>\d+)/delete/$", views.CollabThreadDeleteView.as_view(),
        name="thread_delete"),
]

collab_messages/models.py
from django.db import models
from django.urls import reverse

from pinax.messages.models import Message, Thread

# Create your models here.

class CollabThread(Thread):
    """ Proxy model of the original. We just need to redirect get_absolute_url().
    """

    class Meta:
        proxy = True

    def get_absolute_url(self):
        return reverse("collab_messages:thread_detail", args=[self.pk])


class CollabMessage(Message):
    """ Proxy model of the original. We just need to redirect get_absolute_url().
    """

    class Meta:
        proxy = True

    def get_absolute_url(self):
        return CollabThread.objects.get(pk=self.thread.pk).get_absolute_url()

collab_messages/views.py
from django.urls import reverse_lazy
from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy

from pinax.messages.views import InboxView, MessageCreateView, ThreadDeleteView, ThreadView

from .models import CollabThread, CollabMessage
from .util import get_accessible_users

class CollabInboxView(InboxView):

    template_name = "collab_messages/inbox.html"

    def get_context_data(self, **kwargs):
        context = super(CollabInboxView, self).get_context_data(**kwargs)
        context.update({
            "threads": CollabThread.ordered(CollabThread.inbox(self.request.user)),
            "threads_unread": CollabThread.ordered(CollabThread.unread(self.request.user))
        })
        return context


class CollabMessageCreateView(MessageCreateView):

    template_name = "collab_messages/message_create.html"

    def get_success_url(self):
        return CollabMessage.objects.get(pk=self.object.pk).get_absolute_url()

    def form_valid(self, form):
        # check whether the current user is really allowed to contact to_user
        # this is only needed if the user tampered with user ids in the page source
        accessible_users = get_accessible_users(self.request.user)
        if form.cleaned_data['to_user'] in accessible_users:
            print (dir(form.cleaned_data['to_user']))
            return super(CollabMessageCreateView, self).form_valid(form)
        else:
            form.add_error('to_user', _('You can only write to users you share a group with.'))
            return self.form_invalid(form)


class CollabThreadDeleteView(ThreadDeleteView):

    success_url = reverse_lazy("collab_messages:inbox")
    template_name = "collab_messages/thread_confirm_delete.html"


class CollabThreadView(ThreadView):

    model = CollabThread
    template_name = "collab_messages/thread_detail.html"
    success_url = reverse_lazy("collab_messages:inbox")


# for field label translations
ugettext_lazy("To user")
ugettext_lazy("Subject")

collab_messages/templates/collab_messages/base.html
{% extends 'base.html' %}

{% load i18n sekizai_tags staticfiles %}

{% block body_class %}{{ block.super }} messages{% endblock %}

{% block navbar_links %}
<li>
	<a href="{% url 'collab_user_views:dashboard' %}">{% trans 'Dashboard' %}</a>
</li>
<li class="active">
	<a href="{% url 'collab_messages:inbox' %}">{% trans 'Messages' %}</a>
</li>

{% endblock navbar_links %}

collab_messages/templates/collab_messages/inbox.html
{% extends 'collab_messages/base.html' %}


{% load i18n collab_tags collab_messages_tags pinax_messages_tags %}
{% block content %}
<div class="col-md-12">
<h1>{% trans 'Inbox' %} <small class="text-muted">{% trans 'for' %} {{ user|nice_name }}</small></h1>
</div>
<div class="col-md-3">
	<div class="panel panel-default">
    	<div class="panel-body">
			<a class="btn btn-primary" 
			href="{% url "collab_messages:message_create" %}"
			><span class="icon icon-new-message"></span> {% trans 'New message' %}</a>
		</div>
	</div>
</div>

<div class="col-md-9">
	<div class="list-group media-list media-list-stream">
        {% for thread in threads %}
			<a class="list-group-item p-a" href="{{ thread.get_absolute_url }}">
				<span class="media-left">
					<div class="media-object img-profile" style="background:url({{ thread|recipient_avatar:user }});"></div>
				</span>
				<div class="media-body">
					<strong>{{ thread|recipient:user|nice_name }}</strong>:
					<strong>{{ thread.subject|truncatechars:50 }}</strong>
					<div class="text-muted pull-right">{{ thread.messages.last.sent_at }}</div>
					<div class="media-body-secondary text-muted">
						{% if thread.latest_message.sender == user %}
							{% with thread|recipient:user|nice_name as addressee %}
							{% blocktrans %}{{ addressee }} has not answered yet.{% endblocktrans %}
							{% endwith %}
						{% else %}
							{{ thread.latest_message.content|truncatechars:100 }}
						{% endif %}
						</div>

				</div>
				{% comment %}
	            <div class="thread {% if thread|unread:user %}unread{% endif %}">
	                <a href="{{thread.get_absolute_url}}" >
	                    <div class="row">
	                        <span class="col-sm-2 users">{{ thread.users.all|join:", " }}</span>
	                        <div class="col-sm-10">
	                            <p class="subject">{{ thread.subject }}</p>
	                            <p class="content text-muted">{{ thread.latest_message.content }}</p>
	                        </div>
	                    </div>
	                </a>
	            </div>
				{% endcomment %}
			</a>
        {% empty %}
			<li class="list-group-item p-a">
            <div>{% trans 'You have no messages.' %}</div>
			</li>
        {% endfor %}

	</ul>
</div>

{% endblock %}

collab_messages/templates/collab_messages/includes/accessible_users_select.html
{% load i18n collab_tags sekizai_tags staticfiles %}

<select name="to_user" id="id_to_user" class="selectpicker media-list media-list-stream" data-live-search="true" required>
	<option value="">{% trans 'Select recipient' %}</option>
{% for u in accessible_users %}
  <option 
	value="{{ u.pk }}"
	data-tokens="{{ u.username }} {{ u.first_name }} {{ u.last_name }}"
	data-content="<div class='media'>
					<span class='media-left'>
						<div class='media-object img-profile img-profile-xs' style='background: url({{ u.profile.avatar }});'></div>
					</span>
					<div class='media-body'>
						{{ u|full_nice_name }}
					</div>
				</div>"
	data-icon=""
	>
  </option>
{% endfor %}
</select>

collab_messages/templates/collab_messages/message_create.html
{% extends 'collab_messages/base.html' %}

{% load i18n widget_tweaks collab_messages_tags sekizai_tags staticfiles%}

{% block content %}
<div class="col-md-12">
    <h2>{% trans 'New Message' %}</h2>
</div>

<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-body">
        <a class="btn btn-default" href="{% url 'collab_messages:inbox' %}"><span class="icon icon-level-up"></span> {% trans 'Back to Inbox' %}</a>

        </div>
    </div>
</div>

<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-body">
        <form class="comment-form" action="{% url "collab_messages:message_create" %}" method="post">
            {% csrf_token %}
			 <div class="form-group">
			{% for field in form.visible_fields %}
			  <div class="form-group">
			    <label for="{{ field.id_for_label }}">{% trans field.label %}</label>
				{% if field.name == "to_user" %}
					<br>
					{% accessible_users_select user %}{# NOTE: this needs bootstrap-select.min.js! #}
				{% else %}
				    {{ field|add_class:'form-control'|attr:"required" }}
				{% endif %}
		    	{% for error in field.errors %}
		          <span class="help-block">{{ error }}</span>
			    {% endfor %}
			  </div>
		    {% endfor %}
			</div>
            <button class="btn btn-primary pull-right"><span class="icon icon-check"></span> {% trans 'Send' %}</button>
        </form>
        <a class="btn btn-default" href="{% url "collab_messages:inbox" %}"><span class="icon icon-level-up"></span> {% trans 'Cancel' %}</a>
    </div>
  </div>
</div>
{% endblock %}

{% block custom_js %}
{% addtoblock "js" %}
<script src="{% static 'collab_messages/js/bootstrap-select.min.js' %}"></script>
<script>

$('.selectpicker').val('{{ form.to_user.value }}');
</script>
{% endaddtoblock %}
{% addtoblock "css" %}
<link href="{% static 'collab_messages/css/bootstrap-select.min.css' %}" rel="stylesheet">
{% endaddtoblock %}

{% endblock %}

collab_messages/templates/collab_messages/thread_confirm_delete.html
{% extends 'collab_messages/base.html' %}

{% load i18n %}

{% block head_title %}{% blocktrans with subject=thread.subject %}Confirm Delete: {{ subject }}{% endblocktrans %}{% endblock %}

{% block body %}
<div class="col-xl-6 col-xl-offset-3 col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<div class="panel panel-default">
<div class="panel-body">

    <h1>{% trans "Delete Thread?" %}</h1>

    {% url "collab_messages:thread_delete" thread.pk as post_url %}

    <div class="alert alert-warning" role="alert">

        <p class="lead">
            {% blocktrans with subject=thread.subject %}Are you sure you want to delete thread "{{ subject }}"?{% endblocktrans %}
        </p>

    </div>

    <form action="{{ post_url }}" method="POST" class="form form-horizontal">
        {% csrf_token %}
        <div class="form-actions">
            <a href="{% url "collab_messages:inbox" %}" class="btn">{% trans "Cancel" %}</a>
            <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
        </div>
    </form>

</div>
</div>
</div>
{% endblock %}

collab_messages/templates/collab_messages/thread_detail.html
{% extends "collab_messages/base.html" %}

{% load i18n collab_tags collab_messages_tags widget_tweaks %}

{% block content %}
<div class="col-md-12">
    <h2>{{ thread.subject }}</h2>
</div>
<div class="col-md-3">
	<div class="panel panel-default">
        <div class="panel-body">
		<a class="btn btn-default" href="{% url 'collab_messages:inbox' %}"><span class="icon icon-level-up"></span> {% trans 'Back to Inbox' %}</a>

		</div>
	</div>
</div>

<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-body">
<ul class="media-list media-list-conversation c-w-md">

	<li class="media media-current-user form m-b-md">
		<div class="media-body">
        <form  action="{% url "collab_messages:thread_detail" thread.pk %}" method="post">
            {% csrf_token %}
			{% for field in form.visible_fields %}
			  <div class="form-group">
				{% render_field field rows="2" class+="form-control" %}
			    {% for error in field.errors %}
			      <span class="help-block">{{ error }}</span>
			    {% endfor %}
			  </div>
			{% endfor %}
            <button class="btn btn-primary"><span class="icon icon-check"></span> {% trans 'Send' %}</button>
	        {# <a class="btn btn-default" href="{% url "collab_messages:inbox" %}">{% trans 'Cancel' %}</a> #}
        </form>
		</div>

		 <a class="media-right" href="{% url 'collab_profile:detail' user.pk %}">
            <img class="img-circle media-object" src="{{ user.profile.avatar }}">
        </a>

	</li>




{% for message in thread.messages.all reversed %}
	<li class="media {% if message.sender == user %}media-current-user{% endif %} m-b-md">
		{% if not message.sender == user %}
		<a class="media-left" href="{% url 'collab_profile:detail' message.sender.pk %}">
            <img class="img-circle media-object" src="{{ message.sender.profile.avatar }}">
        </a>
		{% endif %}
    	<div class="media-body">
			<div class="media-body-text">
				{{ message.content|urlize|linebreaks }}
			</div>
			<div class="media-footer">
				<small class="text-muted">
				<a href="{% url 'collab_profile:detail' message.sender.pk %}">{{ message.sender|nice_name }}</a> - {{ message.sent_at }}
				</small>
			</div>
		</div>
		{% if message.sender == user %}
		<a class="media-right" href="{% url 'collab_profile:detail' message.sender.pk %}">
			<img class="img-circle media-object" src="{{ message.sender.profile.avatar }}">
		</a>
		{% endif %}

{% endfor %}
	</li>

	<li class="media m-b-md">
	<a class="btn btn-warning pull-right" href="{% url "collab_messages:thread_delete" thread.pk %}">
	<span class="icon icon-trash"></span>
	{% trans 'Delete Thread' %}</a>
	</li>
</ul>
	</div>
  </div>
</div>
{% endblock %}